server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
    redis:
      host: localhost
      port: 6379
      database: 1

#  # 禁用Langchain4j自动配置
#  autoconfigure:
#    exclude: dev.langchain4j.service.spring.AiServicesAutoConfig


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

## 开启 SQL 日志打印
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    #TODO 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    #微信端
    user-secret-key: itheima
    user-ttl: 720000000
    user-token-name: authentication
  wechat:
    appid: ${sky.jwt.wechat.appid}
    secret: ${sky.jwt.wechat.secret}

  shop:
    address: ${sky.jwt.shop.address}
  baidu:
    ak: ${sky.jwt.baidu.ak}

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: sky-linus
    region: cn-beijing


