sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  jwt:
    wechat:
      appid: wx242f294cec186342
      secret: 8a95fa149ce601ceea030a3f57303640
    shop:
      address: 广东省东莞市松山湖园区大学路1号
    baidu:
      ak: UYsqLF34gEhM9yDpsDvyou2QlhVEeOBg


